### PR TITLE
Simplify sockets

### PR DESCRIPTION
**Pull request by jihgfee**
Removed some fields in the socket record that was never used.

Some outstanding questions:
- How to reflect this in the ML compiler? Should it still take arguments, that it merely throw away?
- Should `Socket` still take a unit argument to simulate that it is "invoked". The current style mimicks the `NewProph` of Iris's HeapLang.

### CODE REVIEW

**Comment by leon-gondelman** [comment]
1. : Ml sources should be reverted I believe. It's the compiler that should take care of translating `socket PF_INET SOCK_DGRAM IPPROTO_UDP `  to `NewSocket ()` or smth like that.

2. I think that `NewSocket` should be a function, if its effect it to allocate a new pointer (surely not in the space of locations, but still it is the same).

**Comment by jihgfee** [comment]
> 1. : Ml sources should be reverted I believe. It's the compiler that should take care of translating `socket PF_INET SOCK_DGRAM IPPROTO_UDP `  to `NewSocket ()` or smth like that.
> 
>     2. I think that `NewSocket` should be a function, if its effect it to allocate a new pointer (surely not in the space of locations, but still it is the same).

1. Would it make sense to have a wrapper in OCaml? Like `udp_socket #() := socket PF_INET SOCK_DGRAM IPPROTO_UDP`. And then we can translate `udp_socket #()` to `NewSocket` (with or without unit argument, depending on where we end up)
It would make the translation more direct.

2. I dont have a strong opinion on unit argument or not.
Argument for is that it looks a bit more like OCaml.
Argument against is that it clutters the opsem with unnecessary stuff.

**Comment by leon-gondelman** [comment]
Sure a wrapper `udp_socket ()` (without '#' ;) ) would be also OK.

**Comment by jihgfee** [comment]
> Sure a wrapper `udp_socket ()` (without '#' ;) ) would be also OK.

I tried to make the wrapper, although I am not entirely sure how the compiler works ^^'.
Can you review?

**Pull request merged**
